In [ ]:
import pandas as pd

# This resource could help you

# Mission 1

![](https://i.imgur.com/Ax3pp2A.png)


Create a "fruit" dataframe that reflects the above example **using a list** data structure

[This resource could help you](https://datatofish.com/list-to-dataframe/).

In [ ]:
fruit = pd.DataFrame([[30, 21]], columns=['Apples', 'Bananas'])
fruit

   Apples  Bananas
0      30       21

# Mission 2

Create a "fruit_vendors" dataframe that reflects the below example **using a dictionary** data structure

![](https://i.imgur.com/CHPn7ZF.png)

[This resource could help you.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html)

In [ ]:
fruit_vendors = pd.DataFrame({
    'Apples': {'2017 Sales': 35, '2018 Sales': 41},
    'Bananas': {'2017 Sales': 21, '2018 Sales': 34},
})
fruit_vendors

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

# Mission 3

Use a loop to display the values from each column in the dataframe from mission 2.

In [ ]:
# There are many, many ways to do this, here's one
for column in fruit_vendors.columns:
  print(column, fruit_vendors[column].values)

Apples [35 41]
Bananas [21 34]

# Mission 4

Delete the first row of the dataframe from mission 2

[This resource could help you.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html)

In [ ]:
# By index, if we know the specific index to drop
fruit_vendors.drop('2017 Sales')

# By location ("drop the first row")
fruit_vendors.drop(fruit_vendors.index[0])

            Apples  Bananas
2018 Sales      41       34

In [ ]:
# Note: the above didn't edit the table!
# You'd have to use inplace=True for the changes to persist, or reassign the table!
fruit_vendors

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

# Mission 5

Delete the first column from the dataframe from mission 2.

In [ ]:
# By column name, if we know the specific one to drop
fruit_vendors.drop(columns='Apples')

# By location ("drop the first colums")
fruit_vendors.drop(columns=fruit_vendors.columns[0])

            Bananas
2017 Sales       21
2018 Sales       34