In [ ]:
import pandas as pd

# Mission 1

Display the following information [for this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user).
- The last 5 rows
- The first 5 rows
- The type of each column

Note : start coding something by typing `pd.read...` and explore the different options available, especially the `sep` parameter.

In [ ]:
# import file and display dataframe
mission1_data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user", sep = "|", names = ["Age", "Gender", "Occupation","Registration Number"])
mission1_data

     Age Gender     Occupation Registration Number
1     24      M     technician               85711
2     53      F          other               94043
3     23      M         writer               32067
4     24      M     technician               43537
5     33      F          other               15213
..   ...    ...            ...                 ...
939   26      F        student               33319
940   32      M  administrator               02215
941   20      M        student               97229
942   48      F      librarian               78209
943   22      M        student               77841

[943 rows x 4 columns]

In [ ]:
# display the last 5 rows
mission1_data.iloc[-5:,:]

     Age Gender     Occupation Registration Number
939   26      F        student               33319
940   32      M  administrator               02215
941   20      M        student               97229
942   48      F      librarian               78209
943   22      M        student               77841

In [ ]:
# display the first 5 rows
mission1_data.iloc[:5,:]

   Age Gender  Occupation Registration Number
1   24      M  technician               85711
2   53      F       other               94043
3   23      M      writer               32067
4   24      M  technician               43537
5   33      F       other               15213

In [ ]:
# display the type of each column
mission1_data.dtypes

Age                     int64
Gender                 object
Occupation             object
Registration Number    object
dtype: object

# Mission 2

Display the first 10 rows [in the following file](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv)

In [ ]:
mission2_data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv",sep = ",")
mission2_data

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,South America
189,Vietnam,111,2,1,2.0,Asia
190,Yemen,6,0,0,0.1,Asia
191,Zambia,32,19,4,2.5,Africa
192,Zimbabwe,64,18,4,4.7,Africa

In [ ]:
# display the first 10 rows
mission2_data.iloc[:10,:]

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe

Set the "country" column as the index for the dataframe.

In [ ]:
mission2_data = mission2_data.set_index('country')
mission2_data

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa
...,...,...,...,...,...
Venezuela,333,100,3,7.7,South America
Vietnam,111,2,1,2.0,Asia
Yemen,6,0,0,0.1,Asia
Zambia,32,19,4,2.5,Africa
Zimbabwe,64,18,4,4.7,Africa

# Mission 3

Access the values of the row for **Zimbabwe** (use the index value)

In [ ]:
mission2_data.loc['Zimbabwe',:]

beer_servings                       64
spirit_servings                     18
wine_servings                        4
total_litres_of_pure_alcohol       4.7
continent                       Africa
Name: Zimbabwe, dtype: object

In [ ]:
mission2_data[mission2_data.index =='Zimbabwe']

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Zimbabwe,64,18,4,4.7,Africa

# Mision 4

Display only the "continent" column value for the country **Zimbabwe**.

In [ ]:
mission2_data.loc['Zimbabwe','continent']

# Mission 5

Rename the columns [of this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv), try using the following 2 different methods to achieve this:
- Setting column names directly when reading the file
- Editing after creating the dataframe ([This resource could be useful](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html))

In [ ]:
mission5_data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv",sep = ",")
mission5_data

In [ ]:
# Setting column name directly when reading the file
mission5_data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv",
                            sep = ",",
                            names = ['Ville','Couleur','Forme','Etat','Temps'],
                            skiprows = 1)
mission5_data

In [ ]:
# Editing after creating the dataframe
mission5_data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv",sep = ",")
mission5_data = mission5_data.rename(columns = {'City':'Ville','Colors Reported':'Couleur','Shape Reported':'Forme','State':'Etat','Time':'Temps'})
mission5_data

# Mission 6

Select the first 3 rows and all the columns of the dataframe using iloc

In [ ]:
mission5_data.iloc[:3,:]

# Mission 7

Achieve the same result as in mission 6 by using loc

In [ ]:
mission5_data.loc[:2]