# Mission 1

![](https://i.imgur.com/Ax3pp2A.png)


Create a "fruit" dataframe that reflects the above example **using a list** data structure

[This resource could help you](https://datatofish.com/list-to-dataframe/).

In [2]:
import pandas as pd

In [5]:
fruits = ["apples", "bananas"]
numbers = [[30,21]]

fruit_df = pd.DataFrame(numbers, columns=fruits)
fruit_df

   apples  bananas
0      30       21

# Mission 2

Create a "fruit_vendors" dataframe that reflects the below example **using a dictionary** data structure

![](https://i.imgur.com/CHPn7ZF.png)

[This resource could help you.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html)

In [8]:
fruits = ["apples", "bananas"]
numbers = [[30,21], [41,34]]
index = ["2017 Sales", "2018 Sales"]

fruit_vendors = pd.DataFrame(numbers, columns=fruits, index=index)
fruit_vendors

            apples  bananas
2017 Sales      30       21
2018 Sales      41       34

# Mission 3

Use a loop to display the values from each column in the dataframe from mission 2.

[This resource could help you](https://www.w3schools.com/python/pandas/ref_df_items.asp)

In [10]:
for i, j in fruit_vendors.items():
    print(i)
    print(j)

apples
2017 Sales    30
2018 Sales    41
Name: apples, dtype: int64
bananas
2017 Sales    21
2018 Sales    34
Name: bananas, dtype: int64

# Mission 4

Delete the first row of the dataframe from mission 2

[This resource could help you.](https://sparkbyexamples.com/pandas/pandas-drop-first-row-of-dataframe/#google_vignette)

In [11]:
fruit_vendors.drop(index="2017 Sales", inplace=True)

fruit_vendors

            apples  bananas
2018 Sales      41       34

# Mission 5

Delete the first column from the dataframe from mission 2.

In [12]:
fruit_vendors = fruit_vendors.drop(columns=fruit_vendors.columns[0])
fruit_vendors

            bananas
2018 Sales       34