# Mission 1

Display the following information [for this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user).
- The last 5 rows
- The first 5 rows
- The type of each column

Note : start coding something by typing `pd.read_csv()` and explore the different options available, especially the `sep` parameter.

In [5]:
import pandas as pd

data_set = pd.read_csv(
    "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user",
    sep="|",
    header=None,
    names=["user_id", "age", "gender", "occupation", "zip_code"],
)


data_set.head(1)

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711

# Mission 2

Display the first 10 rows [in the following file](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv)

In [6]:
data_set_2 = pd.read_csv(
    "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv",
    sep=",",
)

data_set_2.head(10)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe

Set the "country" column as the index for the dataframe, using `set_index` method.

In [7]:
data_set_2.set_index("country", inplace=True)

data_set_2.head(10)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa
Antigua & Barbuda,102,128,45,4.9,North America
Argentina,193,25,221,8.3,South America
Armenia,21,179,11,3.8,Europe
Australia,261,72,212,10.4,Oceania
Austria,279,75,191,9.7,Europe

# Mission 3

Access the values of the row for **Zimbabwe** (use the index value)

In [13]:
data_set_2.loc["Zimbabwe"]

beer_servings                       64
spirit_servings                     18
wine_servings                        4
total_litres_of_pure_alcohol       4.7
continent                       Africa
Name: Zimbabwe, dtype: object

# Mision 4

Display only the "continent" column value for the country **Zimbabwe**.

In [14]:
data_set_2.loc["Zimbabwe"]["continent"]

'Africa'

# Mission 5

Rename the columns [of this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv), try using the following 2 different methods to achieve this:
- Setting column names directly when reading the file
- Editing after creating the dataframe ([This resource could be useful](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html))

In [ ]:
data_set_3 = pd.read_csv(
    "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv",
    sep=",",
    names=['Ville', 'Couleur', 'Forme', 'Etat', 'Heure'],
    header=0
)

data_set_3.head(10)

,Ville,Couleur,Forme,Etat,Heure
0,City,Colors Reported,Shape Reported,State,Time
1,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00
2,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00
3,Holyoke,NaN,OVAL,CO,2/15/1931 14:00
4,Abilene,NaN,DISK,KS,6/1/1931 13:00
5,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00
6,Valley City,NaN,DISK,ND,9/15/1934 15:30
7,Crater Lake,NaN,CIRCLE,CA,6/15/1935 0:00
8,Alma,NaN,DISK,MI,7/15/1936 0:00
9,Eklutna,NaN,CIGAR,AK,10/15/1936 17:00

In [19]:
data_set_4 = pd.read_csv(
    "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv",
    sep=",",
)

data_set_4 = data_set_4.rename(columns={
    "City": "city",
    "Colors Reported": "colors_reported",
    "Shape Reported": "shape_reported",
    "State": "state",
    "Time": "time",
})

data_set_4.head(10)

                   city colors_reported shape_reported state              time
0                Ithaca             NaN       TRIANGLE    NY    6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ   6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO   2/15/1931 14:00
3               Abilene             NaN           DISK    KS    6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY   4/18/1933 19:00
5           Valley City             NaN           DISK    ND   9/15/1934 15:30
6           Crater Lake             NaN         CIRCLE    CA    6/15/1935 0:00
7                  Alma             NaN           DISK    MI    7/15/1936 0:00
8               Eklutna             NaN          CIGAR    AK  10/15/1936 17:00
9               Hubbard             NaN       CYLINDER    OR    6/15/1937 0:00

# Mission 6

Select the first 3 rows and all the columns of the dataframe using iloc

In [21]:
data_set_4.iloc[:3]

          city colors_reported shape_reported state             time
0       Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1  Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2      Holyoke             NaN           OVAL    CO  2/15/1931 14:00

# Mission 7

Achieve the same result as in mission 6 by using loc

In [22]:
data_set_4.loc[:3]

          city colors_reported shape_reported state             time
0       Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1  Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2      Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3      Abilene             NaN           DISK    KS   6/1/1931 13:00